spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/car_tracking_db}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  data:
    redis:
      host: ${REDIS_DATASOURCE_HOST}
      port: ${REDIS_DATASOURCE_PORT:6380}
      password: ${REDIS_DATASOURCE_PASSWORD}
      # ssl: true            
      timeout: 3s

server:
  port: 8080

logging:
  level:
    com.kt_giga_fms.car_tracking: DEBUG
    org.springframework.web: DEBUG
